---

- name: apt install deps
  become: yes
  apt:
    state: latest
    name:
      - vim 
      - zsh
      - ncal
      - curl
      - jq
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - gnupg
      - gitk
      - tree
      - fonts-powerline
  when: ansible_pkg_mgr == 'apt'
  tags:
    - basics

- name: apt install modern-unix
  become: yes
  apt:
    state: latest
    name:
      - bat
      - fzf
      - silversearcher-ag
  when: ansible_pkg_mgr == 'apt'
  tags:
    - modern
- name: Create symbolic link 
  file:
    src: "/usr/bin/batcat"
    dest: "/usr/local/sbin/bat"
    state: link
  become: yes

- name: display shell message
  debug:
    msg:
      - '*******************************************************************************************************'
      - '*******************************************************************************************************'
      - '                                                                                                       '
      - ' Run the following commands if they needed:                                                            '
      - '   curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash         '
      - '   git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k                    '
      - '   echo  "source ~/powerlevel10k/powerlevel10k.zsh-themer" >>~/.zshrc                                  '
      - '                                                                                                       '
      - '                                                                                                       '
      - '                                                                                                       '
      - '*******************************************************************************************************'
      - '*******************************************************************************************************'
