---

- name: Download TFSwitch
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh
    validate_certs: no
    dest: /tmp/tf_install.sh

- name: Run TFSwitch installer
  ansible.builtin.shell:
    cmd: cat /tmp/tf_install.sh | sudo sh -s

- name: add google-cloud-cli apt-key
  become: yes
  apt_key: 
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 
    state: present 

- name: add google-cloud-cli apt repository
  become: yes
  apt_repository: 
    repo: 'deb https://packages.cloud.google.com/apt cloud-sdk main' 
    state: present 
    filename: google-cloud-sdk 
    update_cache: yes

- name: install google-cloud-cli
  become: yes
  apt: 
    name: google-cloud-cli
    state: present
    update_cache: yes

- name: add github-cli apt-key
  become: yes
  apt_key: 
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg 
    state: present 

- name: add github-cli apt repository
  become: yes
  apt_repository: 
    repo: 'deb https://cli.github.com/packages stable main' 
    state: present 
    filename: github-cli 
    update_cache: yes

- name: install github-cli
  become: yes
  apt: 
    name: gh
    state: present
    update_cache: yes
