---

- name: display compile message
  debug:
    msg:
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
      - '***                                                     ***'
      - '*** We are going to compile and install Vim from source ***'
      - '*** Warning: This will try to unistall Vim first        ***'
      - '***                                                     ***'
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
  tags:
    - compile

- name: include task from comile.yml
  include_tasks: compile.yml
  tags:
    - compile

- name: display vimrc message
  debug:
    msg:
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
      - '***                                                     ***'
      - '*** We are going to copy the choosen vimrc file         ***'
      - '***                                                     ***'
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
  tags:
    - vimrc

      # - name: include task from vimrc.yml
      # include_tasks: vimrc.yml
      # tags:
      # - vimrc
