---

- name: display base message
  debug:
    msg:
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
      - '***                                                     ***'
      - '*** We are going to install base software               ***'
      - '***                                                     ***'
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
  tags:
    - base

- name: include task from base.yml
  include_tasks: base.yml
  tags:
    - base
- name: include task from requirements.yml
  include_tasks: requirements.yml
  tags:
    - base

- name: display cloud message
  debug:
    msg:
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
      - '***                                                     ***'
      - '*** We are going to install cloud related software      ***'
      - '***                                                     ***'
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
  tags:
    - cloud

- name: include task from cloud.yml
  include_tasks: cloud.yml
  tags:
    - cloud

- name: display vimrc message
  debug:
    msg:
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
      - '***                                                     ***'
      - '*** We are going to copy the choosen vimrc file         ***'
      - '***                                                     ***'
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
  tags:
    - vimrc

- name: include task from vimrc.yml
  include_tasks: vimrc.yml
  tags:
  - vimrc

- name: display shell message
  debug:
    msg:
      - '*************************************************************************************************************************************************'
      - '*************************************************************************************************************************************************'
      - '                                                                                                                                                 '
      - ' Run the following commands if they needed:                                                                                                      '
      - '   curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash                                                   '
      - '   git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k                                                              '
      - '   echo  "source ~/powerlevel10k/powerlevel10k.zsh-themer" >>~/.zshrc                                                                            '
      - '   git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions                     '
      - '   git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting         '
      - '                                                                                                                                                 '
      - '*************************************************************************************************************************************************'
      - '*************************************************************************************************************************************************'
